#!/bin/ksh
set -a

POWERSENSOR=99
OE=4
POWER=26
CW=29
CCW=27
BRAKE=28

ACTIVATE=0
DEACTIVATE=1

for pin in $POWER $CW $CCW $BRAKE $OE; do
  gpio write $pin 1
  gpio mode $pin output
done
gpio mode $POWERSENSOR input

stopMotors() {
  gpio write $CW  $DEACTIVATE
  gpio write $CCW $DEACTIVATE
}

engageBrake() {
  gpio write $BRAKE 1
}

releaseBrake() {
  gpio write $BRAKE 0
}

